export default {
  "family":{
    "base":"Gilroy",
    "highlight":"Gilroy"
  },
  "size":{
    "us":"12px",
    "xxxs":"14px",
    "xxs":"16px",
    "xs":"20px",
    "sm":"24px",
    "md":"32px",
    "lg":"40px",
    "xl":"48px",
    "xxl":"56px",
    "xxxl":"64px",
    "ul":"80px"
  },
  "weight":{
    "regular":300,
    "medium":500,
    "bold":700
  }
};
